INSERT INTO DEPARTMENT VALUES (1, 'Chairmanship');
INSERT INTO DEPARTMENT VALUES (2, 'Production');
INSERT INTO DEPARTMENT VALUES (3, 'Management');
INSERT INTO DEPARTMENT VALUES (4, 'Security');
COMMIT;